// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMmxL09iNptGpvBp1HF-7lZEFnEOcOwg',
    appId: '1:32483548307:web:afc93b0c9970fdd834c166',
    messagingSenderId: '32483548307',
    projectId: 'meal-planner-mvp',
    authDomain: 'meal-planner-mvp.firebaseapp.com',
    storageBucket: 'meal-planner-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_VeQDjVU1i_-TN1r_WVUc2Ktp5vaQ0g',
    appId: '1:32483548307:android:dd10ce895b55f1d534c166',
    messagingSenderId: '32483548307',
    projectId: 'meal-planner-mvp',
    storageBucket: 'meal-planner-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9AhJRYWZ6gCedDq0ojucC8_GilnC0Jc',
    appId: '1:32483548307:ios:6110b18d2c46781534c166',
    messagingSenderId: '32483548307',
    projectId: 'meal-planner-mvp',
    storageBucket: 'meal-planner-mvp.firebasestorage.app',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj9AhJRYWZ6gCedDq0ojucC8_GilnC0Jc',
    appId: '1:32483548307:ios:6110b18d2c46781534c166',
    messagingSenderId: '32483548307',
    projectId: 'meal-planner-mvp',
    storageBucket: 'meal-planner-mvp.firebasestorage.app',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeMmxL09iNptGpvBp1HF-7lZEFnEOcOwg',
    appId: '1:32483548307:web:a9a85fa69e03175434c166',
    messagingSenderId: '32483548307',
    projectId: 'meal-planner-mvp',
    authDomain: 'meal-planner-mvp.firebaseapp.com',
    storageBucket: 'meal-planner-mvp.firebasestorage.app',
  );
}
